export const LOGIN = 'LOGIN';

export const LOGIN_ATTEMPT = 'LOGIN_REQUEST';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const LOGOUT = 'LOGOUT';
export const LOGIN_FORM_UPDATE = 'LOGIN_FORM_UPDATE';
export const LOGIN_FORM_RESET = 'LOGIN_FORM_RESET';

export const SIGNUP = 'SIGNUP'
export const SIGNUP_LOADING = 'LOADING_SIGNUP';
export const SIGNUP_FORM_UPDATE = 'SIGNUP_FORM_UPDATE';
export const SIGNUP_FORM_RESET = 'SIGNUP_FORM_RESET';
